language: elixir
elixir:
  - 1.5
otp_release:
  - 20.0
  - 19.3
dist: trusty
sudo: required
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS ex_activity_test;'
script: MIX_ENV=travis mix ecto.create && mix ecto.migrate && mix credo && travis mix test
