language: elixir
elixir:
  - 1.5
  - 1.4
otp_release:
  - 20.0
  - 19.3
  - 18.3
dist: trusty
sudo: required
services:
  - msyql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS ex_activity_test;'
script: MIX_ENV=travis mix test && mix credo
