language: elixir
elixir:
  - 1.5
  - 1.4
otp_release:
  - 20.0
  - 19.3
  - 18.3
dist: trusty
sudo: required
services:
  - msyql
before_install:
  - mysql -e 'CREATE DATABASE ex_activity_test;'
matrix:
  exclude:
    - elixir: 1.3
      otp_release: 20.0
script: mix test && mix credo
